name: awesome_cafe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  html: ^0.15.0
  http: ^0.13.4
  webview_flutter: ^3.0.4
  map: ^1.1.0
  latlng: any
  cached_network_image: ^3.2.0
  flutter_svg: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.3
# flutter_native_splash 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  fullscreen: true

# flutter_launcher_icons 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true

assets:
  - assets/
